#! /usr/bin/env sh
#
# Example panel for lemonbar

. panel_colors

datetime=$(date "+%a %b %d %R")
wm="---"
wifi="nowifi"
bth="nobth"
vol="novol"
bl=""
bat=""
[ -z "$(lsblk -o mountpoint | grep "${GNUPGHOME}/mnt")" ] && keys="" || keys="%{F#ff0000}\U000f1574%{F-}"

while true; do
    while read -r line; do
	case $line in
	    KEYS*)
		[ -n "$keys" ] && keys="" || keys="%{F#ff0000}\U000f1574%{F-}"
		;;
	    BAT*)
		# battery output
		bat=$(bar-prettify-battery "${line}")
		;;
	    SYS*)
		# clock output
		datetime="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG} ${sys_icon} ${line#???} %{B-}%{F-}"
		;;
	    BLIGHT*)
		# backlight output
		backlight="${line#??????}"
		backlight="${backlight%.*}%%"
		bl_icon="\U000f1802"
		bl="%{F${COLOR_BACKLIGHT}}${bl_icon} ${backlight}%{F-}"
		;;
	    VOL*)
		# volume
		vol=$(bar-prettify-volume "${line}")
		;;
	    BTH*)
		bth="${line#???}"
		if [[ ${bth} == "yes" ]]
		then
		    bth="%{F${COLOR_BTH}}\U000f00b0%{F-}"
		else
		    bth=""
		fi
		;;
	    WIFI*)
		wifi=$(bar-prettify-wifi "${line}")
		;;
	    W*)
		# bspwm's state
		wm=$(bar-prettify-wm "${line}")
		;;
	esac
	# Final output
	echo -e "%{l}${datetime} | ${wm}%{c}%{r}${keys} ${wifi} ${bth} ${vol} ${bl} ${bat}"
	sleep 0.1
    done
    sleep 0.1
done
