;;; Compiled snippets and support files for `latex-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'latex-mode
		     '(("'z" "\\zeta " "zeta-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/zeta-lower" nil nil)
		       ("gX" "\\Xi" "xi-upper" nil nil nil "/home/ratyaa/.snippets/latex-mode/xi-upper" nil nil)
		       ("gx" "\\xi" "xi-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/xi-lower" nil nil)
		       ("'vt" "\\vartheta " "vartheta-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/vartheta-lower" nil nil)
		       ("'vs" "\\varsigma " "varsigma-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/varsigma-lower" nil nil)
		       ("'vr" "\\varrho " "varrho-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/varrho-lower" nil nil)
		       ("gvf" "\\varphi" "varphi-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/varphi-lower" nil nil)
		       ("gve" "\\varepsilon" "varepsilon-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/varepsilon-lower" nil nil)
		       ("'U" "\\Upsilon " "upsilon-upper" nil nil nil "/home/ratyaa/.snippets/latex-mode/upsilon-upper" nil nil)
		       ("'u" "\\upsilon " "upsilon-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/upsilon-lower" nil nil)
		       ("~" "\\tilde{$0}" "tilde" nil nil nil "/home/ratyaa/.snippets/latex-mode/tilde" nil nil)
		       ("'T" "\\Theta " "theta-upper" nil nil nil "/home/ratyaa/.snippets/latex-mode/theta-upper" nil nil)
		       ("'t" "\\theta " "theta-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/theta-lower" nil nil)
		       (".sum" "\\sum_{$1}^{$2} $0" "sum" nil nil nil "/home/ratyaa/.snippets/latex-mode/sum" nil nil)
		       ("?sss" "\\subsubsection{$0}" "subsubsection" nil nil nil "/home/ratyaa/.snippets/latex-mode/subsubsection" nil nil)
		       ("?ss" "\\subsection{$0}" "subsection" nil nil nil "/home/ratyaa/.snippets/latex-mode/subsection" nil nil)
		       ("'|" "\\left. $0 \\right|_{$1}^{$2}" "statebar" nil nil nil "/home/ratyaa/.snippets/latex-mode/statebar" nil nil)
		       ("'S" "\\Sigma " "sigma-upper" nil nil nil "/home/ratyaa/.snippets/latex-mode/sigma-upper" nil nil)
		       ("'s" "\\sigma " "sigma-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/sigma-lower" nil nil)
		       (".sf" "\\sfrac{$1}{$2}$0" "sfrac" nil nil nil "/home/ratyaa/.snippets/latex-mode/sfrac" nil nil)
		       ("?s" "\\section{$0}" "section" nil nil nil "/home/ratyaa/.snippets/latex-mode/section" nil nil)
		       ("'r" "\\rho " "rho-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/rho-lower" nil nil)
		       ("gP" "\\Pi " "pi-upper" nil nil nil "/home/ratyaa/.snippets/latex-mode/pi-upper" nil nil)
		       ("gp" "\\pi" "pi-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/pi-lower" nil nil)
		       ("'F" "\\Phi " "phi-upper" nil nil nil "/home/ratyaa/.snippets/latex-mode/phi-upper" nil nil)
		       ("'f" "\\phi " "phi-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/phi-lower" nil nil)
		       (".tpd" "\\left(\\frac{\\partial^{$1} $3}{\\partial $4^{$1}}\\right)_{$2}$0" "partial-deriv-thermo" nil nil nil "/home/ratyaa/.snippets/latex-mode/partial-deriv-thermo" nil nil)
		       (".pd" "\\frac{\\partial^{$1} $2}{\\partial $3^{$1}} $0" "partial-deriv" nil nil nil "/home/ratyaa/.snippets/latex-mode/partial-deriv" nil nil)
		       (".p" "\\partial " "partial" nil nil nil "/home/ratyaa/.snippets/latex-mode/partial" nil nil)
		       ("ott" "\\rightarrow" "operator-tendsto" nil nil nil "/home/ratyaa/.snippets/latex-mode/operator-tendsto" nil nil)
		       ("oi" "\\Rightarrow" "operator-implies" nil nil nil "/home/ratyaa/.snippets/latex-mode/operator-implies" nil nil)
		       ("od" "\\hookrightarrow" "operator-does" nil nil nil "/home/ratyaa/.snippets/latex-mode/operator-does" nil nil)
		       ("oa" "\\approx" "operator-approx" nil nil nil "/home/ratyaa/.snippets/latex-mode/operator-approx" nil nil)
		       ("gn" "\\nu " "nu-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/nu-lower" nil nil)
		       ("problem" "\\subsubsection*{$1}\n\\subsubsection*{Условие}\n$0\n\\subsubsection*{Решение}\n\n\\textbf{Ответ:}" "new-problem" nil nil nil "/home/ratyaa/.snippets/latex-mode/new-problem" nil nil)
		       ("sn" "\\mathbb{N}" "natural-set" nil nil nil "/home/ratyaa/.snippets/latex-mode/natural-set" nil nil)
		       ("eem" "\\begin{multline*}\n$0\n\\end{multline*}" "multiline" nil nil nil "/home/ratyaa/.snippets/latex-mode/multiline" nil nil)
		       ("'m" "\\mu " "mu-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/mu-lower" nil nil)
		       (".lim" "\\lim_{$1}$0" "limit" nil nil nil "/home/ratyaa/.snippets/latex-mode/limit" nil nil)
		       ("'()" "\\left($1 \\right) $0" "left-right-parens" nil nil nil "/home/ratyaa/.snippets/latex-mode/left-right-parens" nil nil)
		       ("'[]" "\\left[$1 \\right] $0" "left-right-brackets" nil nil
			((yas-indent-line 'fixed)
			 (yas-wrap-around-region 't))
			"/home/ratyaa/.snippets/latex-mode/left-right-brackets" nil nil)
		       ("'{}" "\\left\\\\{$1 \\right\\\\} $0" "left-right-braces" nil nil nil "/home/ratyaa/.snippets/latex-mode/left-right-braces" nil nil)
		       ("'L" "\\Lambda " "lambda-upper" nil nil nil "/home/ratyaa/.snippets/latex-mode/lambda-upper" nil nil)
		       ("gl" "\\lambda" "lambda-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/lambda-lower" nil nil)
		       ("'k" "\\kappa " "kappa-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/kappa-lower" nil nil)
		       ("'i" "\\iota " "iota-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/iota-lower" nil nil)
		       (".int" "\\int_{$1}^{$2} $0\\; \\mathrm{d} $3" "integral" nil nil nil "/home/ratyaa/.snippets/latex-mode/integral" nil nil)
		       ("si" "\\infty" "infinity" nil nil nil "/home/ratyaa/.snippets/latex-mode/infinity" nil nil)
		       ("^" "\\hat{$0}" "hat" nil nil nil "/home/ratyaa/.snippets/latex-mode/hat" nil nil)
		       ("eg" "\\begin{gather*}\n$0\n\\end{gather*}" "gather" nil nil nil "/home/ratyaa/.snippets/latex-mode/gather" nil nil)
		       ("gG" "\\Gamma" "gamma-upper" nil nil nil "/home/ratyaa/.snippets/latex-mode/gamma-upper" nil nil)
		       ("gg" "\\gamma" "gamma-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/gamma-lower" nil nil)
		       (".dd" "\\frac{\\mathrm{d}^{$1} $2}{\\mathrm{d} $3^{$1}} $0\n" "full-deriv" nil nil nil "/home/ratyaa/.snippets/latex-mode/full-deriv" nil nil)
		       (".f" "\\frac{$1}{$2}$0" "frac" nil nil nil "/home/ratyaa/.snippets/latex-mode/frac" nil nil)
		       ("'h" "\\eta" "eta-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/eta-lower" nil nil)
		       ("?et" "\\begin{equation} \\label{eq:$1} \\tag{($2)}\n$0\n\\end{equation}" "equation-labeled-taged" nil nil nil "/home/ratyaa/.snippets/latex-mode/equation-labeled-taged" nil nil)
		       ("?e" "\\begin{equation} \\label{eq:$1}\n$0\n\\end{equation}" "equation-labeled" nil nil nil "/home/ratyaa/.snippets/latex-mode/equation-labeled" nil nil)
		       ("ee" "\\begin{equation*}\n$0\n\\end{equation*}" "equation" nil nil nil "/home/ratyaa/.snippets/latex-mode/equation" nil nil)
		       ("ge" "\\epsilon" "epsilon-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/epsilon-lower" nil nil)
		       ("enuma" "\\begin{enumerate}[label=\\asbuk*)]\n\\item $0\n\\end{enumerate}" "enumerate-asbuka" nil nil nil "/home/ratyaa/.snippets/latex-mode/enumerate-asbuka" nil nil)
		       ("enum" "\\begin{enumerate}[$1]\n\\item $0\n\\end{enumerate}" "enumerate" nil nil nil "/home/ratyaa/.snippets/latex-mode/enumerate" nil nil)
		       (".d" "\\mathrm{d} " "diff" nil nil nil "/home/ratyaa/.snippets/latex-mode/diff" nil nil)
		       ("gD" "\\Delta " "delta-upper" nil nil nil "/home/ratyaa/.snippets/latex-mode/delta-upper" nil nil)
		       ("gd" "\\delta " "delta-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/delta-lower" nil nil)
		       ("tb" "\\textbf{$0}" "bold-text" nil nil nil "/home/ratyaa/.snippets/latex-mode/bold-text" nil nil)
		       ("`b" "\\boldsymbol{$1} $0" "bold-math" nil nil nil "/home/ratyaa/.snippets/latex-mode/bold-math" nil nil)
		       ("gb" "\\beta" "beta-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/beta-lower" nil nil)
		       ("ga" "\\alpha" "alpha-lower" nil nil nil "/home/ratyaa/.snippets/latex-mode/alpha-lower" nil nil)
		       ("sea" "\\begin{aligned}\n$0\n\\end{aligned}" "aligned" nil nil
			((yas-wrap-around-region t))
			"/home/ratyaa/.snippets/latex-mode/aligned" nil nil)
		       ("ea" "\\begin{align*}\n$0\n\\end{align*}" "align" nil nil nil "/home/ratyaa/.snippets/latex-mode/align" nil nil)
		       ("Rn" "\\mathbb{R}^{$0}" "Rn" nil nil nil "/home/ratyaa/.snippets/latex-mode/Rn" nil nil)))


;;; Do not edit! File generated at Thu Mar 30 18:43:23 2023
