alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias l='ls -la'
alias e='emacsclient -c'
alias et='emacsclient -c -t'
alias er='emacsclient -e "(kill-emacs)" && emacs --daemon'
alias tsm='transmission-remote'
alias fcd='cd "$(find -type d | fzf)"'
alias open='xdg-open "$(find -type f |fzf)"'
alias getpath='find -type f | fzf | sed "s/^..//" | tr -d "\n" | xclip -selection c'
alias dots='git --git-dir=$HOME/.dots/ --work-tree=$HOME'
alias passgit='git --git-dir=$HOME/.password-store/.git --work-tree=$HOME/.password-store'
alias yapassgen='head /dev/urandom | tr -dc '\''A-Za-z0-9`!@#$%^&*()_=+[]{};:"\|,.'\'' | head -c 80'
