#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x panel > /dev/null || panel &

bspc monitor $BSPWM_MONITOR_LIST -d 一 二 三 四 五 六 七 八 九

bspc config focused_border_color "#d79921" # yellow
bspc config focused_border_color "#b1a57d" # default (gray)

bspc config border_width 2
bspc config window_gap 12
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Emacs state=tiled

bspc rule -a Zathura rectangle=1238x1612+1266+52 # border version
# bspc rule -a Zathura rectangle=1260x1640+1260+40
bspc rule -a Zathura state=tiled
# bspc rule -a Nyxt state=pseudo_tiled

bspc rule -a Discord desktop=^8 follow=off
bspc rule -a Telegram desktop=^9 follow=off

# exec discord
# exec telegram-desktop
